// test-apps/todo/src/react/AddTodo.tsx
import React from "react";
import { Button } from "./Button";

export const AddTodo = (props: { addTodo: (text: string) => void }) => {
  const [text, setText] = React.useState("");

  return (
    <div className="add-todo">
      <input
        type="text"
        value={text}
        onChange={(e) => setText(e.target.value)}
        placeholder="Enter a new todo..."
      />
      <Button
        onClick={() => {
          if (text.trim() === "") return;
          props.addTodo(text);
          setText("");
        }}
        disabled={text.trim() === ""}
      >
        Add
      </Button>
    </div>
  );
};

// test-apps/todo/src/svelte/AddTodo.svelte
<script lang="ts">
  import Button from "./Button.svelte";

  export let addTodo: (text: string) => void;

  let text = "";
</script>

<div class="add-todo">
  <input type="text" bind:value={text} placeholder="Enter a new todo..." />
  <Button
    onClick={() => {
      if (text.trim() === "") return;
      addTodo(text);
      text = "";
    }}
    disabled={text.trim() === ""}
  >
    Add
  </Button>
</div>
