// demo/react/tree/src/components/TreeNode.tsx
import { useCallback, useRef, useState } from 'react';

const TreeNode = (props: { id: number; removeNode?: (id: number) => void }) => {
	const removeNodeFromParent = props.removeNode;

	const [treeNodes, setTreeNodes] = useState<number[]>([]);
	const nodeIdRef = useRef(0);

	const [counter, setCounter] = useState<number>(0);

	const removeNode = useCallback((id: number) => {
		setTreeNodes((treeNodes) => treeNodes.filter((nodeId) => nodeId !== id));
	}, []);

	return (
		<div style={{ border: '1px solid black', padding: '1rem' }}>
			{props.id}
			{removeNodeFromParent && <button onClick={() => removeNodeFromParent(props.id)}>Remove</button>}
			<button
				onClick={() => {
					setTreeNodes([...treeNodes, nodeIdRef.current++]);
				}}
			>
				Add
			</button>
			{counter}
			<button onClick={() => setCounter(counter + 1)}>State</button>
			<div
				style={{
					display: 'flex',
					justifyContent: 'space-evenly',
				}}
			>
				{treeNodes.map((nodeId) => (
					<TreeNode key={nodeId} id={nodeId} removeNode={removeNode} />
				))}
			</div>
		</div>
	);
};

export default TreeNode;

// demo/svelte/tree/src/lib/TreeNode.svelte
<script lang="ts">
  export let id: number;
  export let removeNode: ((id: number) => void) | undefined = undefined;

  let currentId: number = 0;
  let treeNodes: number[] = [];
  let count: number = 0;

  const remove = (idToRemove: number) => {
    treeNodes = treeNodes.filter((nodeId) => nodeId !== idToRemove);
  };
</script>

<div style:border="1px solid black" style:padding="1rem">
  {id}
  {#if removeNode}
    <button on:click={() => removeNode && removeNode(id)}>Remove</button>
  {/if}
  <button
    on:click={() => {
      treeNodes = [...treeNodes, currentId];
      currentId += 1;
    }}
  >
    Add</button
  >
  {count}
  <button on:click={() => (count += 1)}>State</button>
  <div class="children-container">
    {#each treeNodes as nodeId (nodeId)}
      <svelte:self id={nodeId} removeNode={remove} />
    {/each}
  </div>
</div>

<style>
  .children-container {
    display: flex;
    justify-content: space-evenly;
  }
</style>
